### ISSUE TITLE
Cisco devices - which platform to use

### ISSUE THREAD

**Issue by gorbyhail** [netpicker/netpicker#5]
Hey, this is more of a general query than a bug/issue, so apologies if this is the wrong place. There are a lot of cisco platforms and I'm unsure how to match the platform to the device in use, any guidance you're able to give me/otherwise point me in the right direction?

**Comment by gorbyhail** [comment]
Hi Otto,
As an example, we have a lot of SG500X switches in the field. I want to test these within Netpicker, but not sure what platform to specify from those listed within Netpicker and in Netmiko:

- cisco_asa
- cisco_ftd
- cisco_ios
- cisco_nxos
- cisco_s200
- cisco_s300
- cisco_tp
- cisco_viptela
- cisco_wlc
- cisco_xe
- cisco_xr

**Comment by ottocoster** [comment]
According to this link - https://github.com/ktbyers/netmiko/issues/1071 - cisco_s300 is the platform to use

**Comment by gorbyhail** [comment]
Thanks Otto - that appears to be working!
