### ISSUE TITLE
Schedule not work

### ISSUE THREAD

**Issue by CopyBook-Maxim** [netpicker/netpicker#6]
Schedule not work

I put different values in Schedule, but it didn't automatically collect anything. 
If you do Schedule now manually, the config is collected.

I also could not find the time zone settings, neither through Web UI, nor through docker-compose.yml.
At the same time, the Date in the collected config shows the correct time.

**Comment by ottocoster** [comment]
Yeah, this needs some explanation. The schedule is a cron job that runs on the server you installed Netpicker on, so it uses the server time for the crontab details. In the UI, we display the 'Last run at' in your local timezone (of your web browser). This might be different and probably explains why you don't see it collecting anything yet.

<img width="1320" alt="image" src="https://github.com/user-attachments/assets/e308a2f2-0451-4ab4-94b5-57127cbd3ff8">

**Comment by CopyBook-Maxim** [comment]
> Yeah, this needs some explanation. The schedule is a cron job that runs on the server you installed Netpicker on, so it uses the server time for the crontab details. In the UI, we display the 'Last run at' in your local timezone (of your web browser). This might be different and probably explains why you don't see it collecting anything yet.
> 
> <img alt="image" width="1320" src="https://private-user-images.githubusercontent.com/48188762/360329451-e308a2f2-0451-4ab4-94b5-57127cbd3ff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Njc4NTEsIm5iZiI6MTcyNDc2NzU1MSwicGF0aCI6Ii80ODE4ODc2Mi8zNjAzMjk0NTEtZTMwOGEyZjItMDQ1MS00YWI0LTk0YjUtNTcxMjdjYmQzZmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE0MDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNGI1NmI4YzYwNmE4YWI2N2FlNmNjOGMwOWMwMzkwMzBiY2FiY2UzYjY0YTg3MzIxYWIwN2Y2NGIwNWI0MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AatHq5oY_dcb5SL-wVPV1OJKCXaRL3GF9zfAdfS-VCw">




Good afternoon.

I put in a few days. But nothing has changed. Zero launches. 

My configuration:

![image](https://github.com/user-attachments/assets/b1792eaf-1198-4826-9d21-bd6cabfef55c)

![image](https://github.com/user-attachments/assets/a7fd70fb-5596-4876-9824-f74584a314aa)

When manually starting, the Runs counter also does not increase. but configuration is backup.

Where could I have missed some configuration?)

**Comment by ottocoster** [comment]
Are you running the latest version (2024-08-26)? We fixed some bugs in the backup process.

Check how to update here on our release notes page: https://netpicker.io/knowledge-base/release-notes/

**Comment by CopyBook-Maxim** [comment]
Yes, I updated and Schedule is now working correctly. The time is set according to the time zone of the server, I'll take care of that.
 
Thank you!

**Comment by CopyBook-Maxim** [comment]
Yes, I updated and Schedule is now working correctly. The time is set according to the time zone of the server, I'll take care of that.
 
Thank you!
